# Generated by Django 4.1.4 on 2023-05-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('selected', models.CharField(max_length=50, verbose_name='email')),
                ('info', models.TextField(verbose_name='Додаткова інформація')),
                ('data_public', models.DateField(verbose_name='Дата замовлення')),
            ],
        ),
    ]
