# Generated by Django 4.1.4 on 2023-05-04 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='data_public',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата замовлення'),
        ),
    ]
