# Generated by Django 4.1.4 on 2023-05-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_alter_service_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='service',
            name='selected',
            field=models.CharField(max_length=50, verbose_name='Категорія реклами'),
        ),
    ]
